ENCODER_MAP_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = ssd1306
LTO_ENABLE = yes  # Makes hex file smaller
SPLIT_KEYBOARD = yes

WS2812_DRIVER_REQUIRED = yes
#CUSTOM_RGB = yes

RGBLIGHT_ENABLE = yes

#RGB_MATRIX_ENABLE = yes
#RGB_MATRIX_CUSTOM_USER = yes


WPM_ENABLE = yes

TAP_DANCE_ENABLE = yes

MOUSEKEY_ENABLE = yes

#CONSOLE_ENABLE=yes